In [2]:
# http://www.bkjia.com/ASPjc/944250.html
import numpy as np

In [3]:
print np.__version__

1.11.3


In [4]:
print np.__config__.show()

lapack_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/home/nco/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/nco/anaconda2/include']
blas_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/home/nco/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/nco/anaconda2/include']
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/home/nco/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/nco/anaconda2/include']
blas_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/home/nco/anaconda2/lib']
    define_

In [7]:
z = np.zeros((2,3))
print z

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [8]:
z[1, 2] = 9
print z

[[ 0.  0.  0.]
 [ 0.  0.  9.]]


In [9]:
z = np.arange(1, 101).reshape(10, 10)
print z

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [11]:
nz = np.nonzero(z[0])
print nz

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),)


In [15]:
#generate unit vector using eye function

uv = np.eye(6)
print uv


[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]


In [19]:
vdiag = np.diag([1, 2, 3, 4, 5, 6], k=0)
print vdiag

vdiag = np.diag([1, 2, 3, 4, 5, 6], k=1)
print vdiag

vdiag = np.diag([1, 2, 3, 4, 5, 6], k=-1)
print vdiag


[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]
[[0 1 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 0 3 0 0 0]
 [0 0 0 0 4 0 0]
 [0 0 0 0 0 5 0]
 [0 0 0 0 0 0 6]
 [0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]]


In [21]:
nr = np.random.random((3, 3))
print nr

[[ 0.10125926  0.87465648  0.17322101]
 [ 0.82370279  0.19901731  0.46285047]
 [ 0.63989712  0.22917112  0.16570477]]


In [24]:
chess8x8 = np.zeros((8, 8), dtype=int)
print chess8x8
chess8x8[1::2, ::2]=1
print chess8x8

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


In [26]:
zmin, zmax = nr.min(), nr.max()
print zmin, zmax

0.101259258965 0.874656484176


In [27]:
z = np.tile(np.array([[0, 1], [0, 1]]), (4, 4))
print z


[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [29]:
z = np.random.random((5, 5))
print z
zmin, zmax = z.min(), z.max()
z = (z - zmin)/(zmax-zmin)
print z


[[ 0.85035518  0.46288616  0.55581744  0.19526213  0.41176131]
 [ 0.5986084   0.22200761  0.94865801  0.99862143  0.20656256]
 [ 0.13213444  0.95647527  0.81284435  0.32473754  0.63045425]
 [ 0.37385268  0.74547643  0.08467626  0.84154606  0.02334591]
 [ 0.63873464  0.2462396   0.74347817  0.88797295  0.10193171]]
[[ 0.847975    0.45068315  0.54597036  0.17627452  0.39826222]
 [ 0.58984613  0.20369803  0.94876994  1.          0.18786143]
 [ 0.11154646  0.95678538  0.80951323  0.30903229  0.62249931]
 [ 0.35939256  0.74043745  0.06288516  0.83894256  0.        ]
 [ 0.63098962  0.22854433  0.73838853  0.88654643  0.08057805]]


In [35]:
z = np.dot(np.ones((5, 3)), np.ones((3, 2))+1)
print z
                              

[[ 6.  6.]
 [ 6.  6.]
 [ 6.  6.]
 [ 6.  6.]
 [ 6.  6.]]
